name=Hot Bean Juice
mod_id=hotbeanjuice

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

forge_version=1.18.2-40.2.17
mcp_channel=official
mcp_mappings=1.18.2
parchment_version=2022.11.06-1.18.2
jupiter_version=5.8.1
# for the Apple Silicon plugin
mc_version=1.18.2
target_mc_version=1.18.2
base_mc_version=1.18
additional_mc_versions=1.18

fml_version_range=[40,)
forge_version_range=[40.2.17,)
minecraft_version_range=[1.18.2, 1.19)

curseforge_project_id=968123
curseforge_release_type=alpha

modrinth_project_id=sqqCq3AL
modrinth_release_type=alpha

# JEI
jei_version=9.7.2.281
# Farmer's Delight
farmers_project_id=398521
farmers_file_id=4679315
# Ars Nouveau
ars_project_id=401955
ars_file_id=4543053
curios_project_id=309927
curios_file_id=4985315
# Create
create_project_id=328085
create_file_id=5797603
# The One Probe
top_project_id=245211
top_file_id=3671753
# Patchouli
ptch_version=1.18.2-71.1
ptch_file_id=3729975
# Celestial Exploration
cexp_project_id=577208
cexp_file_id=5969833
azure_project_id=817423
azure_file_id=5782731
# Craft Tracker
ctrk_project_id=626455
ctrk_file_id=6011800
# Super Secret Doors
ssd_project_id=951809
ssd_file_id=5976201
# Cat Herder
ch_project_id=580311
ch_file_id=5060243
# Quark
qrk_project_id=243121
qrk_file_id=3840125
arl_project_id=250363
arl_file_id=3642382
