modLoader="javafml"
loaderVersion="${fml_version_range}"
license="MIT"
issueTrackerURL="https://github.com/sweetrpg/HotBeanJuice/issues"
displayURL="https://minecraft.curseforge.com/projects/hot-bean-juice/"
logoFile= "hbj_logo.png"

[[mods]]
    modId="hotbeanjuice"
    version="${version}"
    updateJSONURL="https://minecraft.sweetrpg.com/mods/hotbeanjuice/version.json"
    displayName="Hot Bean Juice"
    credits="paulyhedral shimaginary primal_zerg_"
    authors="paulyhedral shimaginary primal_zerg_"
    description='''
    Coffee!
    '''
[[dependencies.hotbeanjuice]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.hotbeanjuice]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.hotbeanjuice]]
    modId="configured"
    mandatory=false
    versionRange="[1.5.4,)"
    ordering="NONE"
    side="BOTH"

[modproperties.configured]
    catalogueImageIcon="configured_icon.png"
    configuredBackground="minecraft:textures/block/gray_wool.png"
